[package]
id = TA_ubnt_unifi

[install]
is_configured = 0
state = enabled

[ui]
is_visible = false
label = Ubiquiti UniFi Add-on for Splunk

[launcher]
author = Tomas Moser
description = Knowledge objects for Ubiquiti UniFi logs parsed by Splunk Edge Processor
version = 1.0.0
