[ubnt_unifi_gw_firewall]
search = sourcetype=ubnt:unifi:gw:firewall

[ubnt_unifi_gw_firewall_allowed]
search = sourcetype=ubnt:unifi:gw:firewall action="allowed"

[ubnt_unifi_gw_firewall_denied]
search = sourcetype=ubnt:unifi:gw:firewall action="blocked"

[ubnt_unifi_gw_firewall_wan]
search = sourcetype=ubnt:unifi:gw:firewall zone_pair=LAN_WAN

[ubnt_unifi_gw_firewall_local]
search = sourcetype=ubnt:unifi:gw:firewall zone_pair=LAN_LOCAL

[ubnt_unifi_gw_firewall_default_rule]
search = sourcetype=ubnt:unifi:gw:firewall rule_id=2147483647

[ubnt_unifi_ap_wireless]
search = sourcetype=ubnt:unifi:ap:wireless

[ubnt_unifi_ap_wireless_client_anomaly]
search = sourcetype=ubnt:unifi:ap:wireless event_subtype=sta_anomaly

[ubnt_unifi_ap_wireless_sta_tracker]
search = sourcetype=ubnt:unifi:ap:wireless (message_type=STA_ASSOC_TRACKER OR event_subtype=sta_tracker)

[ubnt_unifi_ap_wireless_dns_timeout]
search = sourcetype=ubnt:unifi:ap:wireless event_type="dns timeout"

[ubnt_unifi_ap_wireless_hsm]
search = sourcetype=ubnt:unifi:ap:wireless event_subtype=hsm_scan_transition

[ubnt_unifi_ap_wireless_rrm]
search = sourcetype=ubnt:unifi:ap:wireless event_subtype=rrm_scan_trigger
