[unifi_fw_denied(1)]
definition = sourcetype=ubnt:unifi:gw:firewall action="blocked" $filter$
iseval = 0
args = filter

[unifi_fw_wan_egress(1)]
definition = sourcetype=ubnt:unifi:gw:firewall zone_pair=LAN_WAN $filter$
iseval = 0
args = filter

[unifi_fw_interesting(1)]
definition = sourcetype=ubnt:unifi:gw:firewall NOT rule_id=2147483647 $filter$
iseval = 0
args = filter

[unifi_ap_wireless_clients(1)]
definition = sourcetype=ubnt:unifi:ap:wireless NOT (event_subtype=hsm_scan_transition OR event_subtype=rrm_scan_trigger) $filter$
iseval = 0
args = filter

[unifi_ap_wireless_low_satisfaction(1)]
definition = sourcetype=ubnt:unifi:ap:wireless event_subtype=sta_anomaly satisfaction<80 $filter$
iseval = 0
args = filter

[unifi_ap_wireless_dns_timeouts(1)]
definition = sourcetype=ubnt:unifi:ap:wireless event_type="dns timeout" process=stahtd $filter$
iseval = 0
args = filter
