[ubnt:unifi:gw:firewall]
FIELDALIAS-unifi_src = SRC AS src
FIELDALIAS-unifi_dest = DST AS dest
FIELDALIAS-unifi_src_port = SPT AS src_port
FIELDALIAS-unifi_dest_port = DPT AS dest_port
FIELDALIAS-unifi_transport = PROTO AS transport
FIELDALIAS-unifi_ingress = IN AS ingress_interface
FIELDALIAS-unifi_egress = OUT AS egress_interface
FIELDALIAS-unifi_rule_desc = DESCR AS rule_description

EVAL-vendor_product = "Ubiquiti UniFi"
EVAL-transport = lower(transport)
EVAL-vendor_action_id = case(
    isnotnull(vendor_action_id) AND len(vendor_action_id) > 0, vendor_action_id,
    match(_raw, "\-RET\-"), "RET",
    match(_raw, "\-B\-"), "B",
    match(_raw, "\-R\-"), "R",
    match(_raw, "\-D\-"), "D",
    match(_raw, "\-A\-"), "A",
    true(), null())
LOOKUP-unifi_action = unifi_firewall_action_lookup vendor_action_id OUTPUTNEW vendor_action action
EVAL-zone_pair = case(
    isnotnull(zone_pair) AND len(zone_pair) > 0, zone_pair,
    true(), replace(_raw, "^.*\[([A-Z_]+)-[A-Z]+-\d+\].*$", "\1"))
EVAL-rule_id = case(
    isnotnull(rule_id) AND len(rule_id) > 0, rule_id,
    true(), replace(_raw, "^.*\[[A-Z_]+-[A-Z]+-(\d+)\].*$", "\1"))

[ubnt:unifi:ap:wireless]
FIELDALIAS-unifi_client_mac = mac AS client_mac
FIELDALIAS-unifi_client_mac_sta = sta AS client_mac
FIELDALIAS-unifi_dns_query = query_2 AS query
FIELDALIAS-unifi_dns_query_kernel = query AS query
FIELDALIAS-unifi_dns_server = query_server_2 AS dns_server
FIELDALIAS-unifi_bssid = bssid AS bssid
FIELDALIAS-unifi_vap = vap AS vap

EVAL-vendor_product = "Ubiquiti UniFi"
EVAL-satisfaction = if(isnotnull(satisfaction_now), tonumber(satisfaction_now), null())
