[eventtype=ubnt_unifi_gw_firewall]
network = enabled

[eventtype=ubnt_unifi_gw_firewall_allowed]
network = enabled

[eventtype=ubnt_unifi_gw_firewall_denied]
network = enabled

[eventtype=ubnt_unifi_ap_wireless_dns_timeout]
resolve = enabled
network = enabled
