[unifi_firewall_action_lookup]
filename = unifi_firewall_action_map.csv
case_sensitive_match = true
match_type = EXACT
max_matches = 1
default_match = unknown

[unifi_fw_mac_fields]
REGEX = MAC=(?<src_mac>[0-9A-Fa-f]{2}(?::[0-9A-Fa-f]{2}){5}):(?<dest_mac>[0-9A-Fa-f]{2}(?::[0-9A-Fa-f]{2}){5}):(?<ether_type>[0-9A-Fa-f]{2}:[0-9A-Fa-f]{2})
